In [2]:
import numpy as np
import math

# Given values
a = 1 / math.sqrt(2)
b = 1 / math.sqrt(2)

# Create vector
v = np.array([a, b])
print("Vector:", v)

# Check normalization
norm_check = a**2 + b**2
print("a^2 + b^2 =", norm_check)

if math.isclose(norm_check, 1.0):
    print("Vector is normalized")
else:
    print("Vector is NOT normalized")

# Length of vector
length = np.linalg.norm(v)
print("Length of vector:", length)


Vector: [0.70710678 0.70710678]
a^2 + b^2 = 0.9999999999999998
Vector is normalized
Length of vector: 0.9999999999999999


In [3]:
import numpy as np

# Read vector from user
n = int(input("Enter size of vector: "))
vec = []

for i in range(n):
    val = float(input(f"Enter element {i+1}: "))
    vec.append(val)

A = np.array(vec)
print("Vector A:", A)

# Function: check normalization
def is_normalized(v):
    return np.isclose(np.sum(v**2), 1)

print("Is normalized?", is_normalized(A))

# Function: dot and cross product
def dot_cross(A, B):
    dot = np.dot(A, B)
    cross = np.cross(A, B)
    return dot, cross

# Input second vector
vec2 = []
for i in range(n):
    val = float(input(f"Enter element {i+1} of vector B: "))
    vec2.append(val)

B = np.array(vec2)

d, c = dot_cross(A, B)
print("Dot product:", d)
print("Cross product:", c)

# Function: unit vector
def unit_vector(v):
    mag = np.linalg.norm(v)
    if mag == 0:
        return "Zero vector has no unit vector"
    return v / mag

print("Unit vector of A:", unit_vector(A))


Enter size of vector: 3
Enter element 1: 1
Enter element 2: 2
Enter element 3: 3
Vector A: [1. 2. 3.]
Is normalized? False
Enter element 1 of vector B: 4
Enter element 2 of vector B: 5
Enter element 3 of vector B: 6
Dot product: 32.0
Cross product: [-3.  6. -3.]
Unit vector of A: [0.26726124 0.53452248 0.80178373]


In [4]:
import numpy as np

r = int(input("Enter rows: "))
c = int(input("Enter columns: "))

mat = []
print("Enter matrix elements row-wise:")
for i in range(r):
    row = []
    for j in range(c):
        row.append(float(input()))
    mat.append(row)

A = np.array(mat)
print("Matrix A:\n", A)

# Transpose
print("Transpose:\n", A.T)

# Determinant (only square)
if r == c:
    print("Determinant:", np.linalg.det(A))

    # Rank
    print("Rank:", np.linalg.matrix_rank(A))

    # Trace
    print("Trace:", np.trace(A))

    # Eigenvalues & Eigenvectors
    vals, vecs = np.linalg.eig(A)
    print("Eigenvalues:\n", vals)
    print("Eigenvectors:\n", vecs)

    # Inverse
    if np.linalg.det(A) != 0:
        print("Inverse:\n", np.linalg.inv(A))
    else:
        print("Matrix is singular, inverse not possible")
else:
    print("Eigen, determinant, inverse only for square matrices")


Enter rows: 2
Enter columns: 2
Enter matrix elements row-wise:
4
7
2
6
Matrix A:
 [[4. 7.]
 [2. 6.]]
Transpose:
 [[4. 2.]
 [7. 6.]]
Determinant: 10.000000000000002
Rank: 2
Trace: 10.0
Eigenvalues:
 [1.12701665 8.87298335]
Eigenvectors:
 [[-0.92511345 -0.82071729]
 [ 0.37969079 -0.57133452]]
Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [5]:
# Read complex number
z = complex(input("Enter a complex number (e.g. 3+4j): "))
print("Complex number:", z)

# Conjugate
print("Conjugate:", z.conjugate())

# Second number
z2 = complex(input("Enter another complex number: "))

print("Addition:", z + z2)
print("Subtraction:", z - z2)
print("Multiplication:", z * z2)
print("Division:", z / z2)

# As 2D vector
print("As 2D vector: (", z.real, ",", z.imag, ")")

# Magnitude
print("Magnitude:", abs(z))


Enter a complex number (e.g. 3+4j): 3+4j
Complex number: (3+4j)
Conjugate: (3-4j)
Enter another complex number: 1-2j
Addition: (4+2j)
Subtraction: (2+6j)
Multiplication: (11-2j)
Division: (-1+2j)
As 2D vector: ( 3.0 , 4.0 )
Magnitude: 5.0
